# Experiment Log Template

experiment:
  id: exp_XXX
  name: "실험 이름 (간결하게)"
  date: YYYY-MM-DD
  author: [담당자 이름]
  goal: |
    이 실험의 목표를 명확히 기술
    예: "YOLOv8m으로 작은 알약 검출 성능 개선"

baseline:
  experiment_id: exp_000  # 비교 대상 실험 (없으면 null)
  score: 0.XXX            # 비교 대상 점수

model:
  architecture: "모델 아키텍처 (예: yolov8m)"
  pretrained: true/false
  backbone: "백본 네트워크 (예: CSPDarknet)"
  input_size: [640, 640]
  num_classes: XX

data:
  train_data: "data/processed/train"
  val_data: "data/processed/val"
  train_size: 0.8
  val_size: 0.2

  augmentation:
    - name: HorizontalFlip
      probability: 0.5
    - name: RandomRotate
      degree: 15
    - name: ColorJitter
      brightness: 0.2
      contrast: 0.2
    - name: RandomScale
      scale: [0.8, 1.2]

  preprocessing:
    resize: [640, 640]
    normalize: true
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

training:
  epochs: 100
  batch_size: 16
  learning_rate: 0.001

  optimizer:
    type: AdamW
    weight_decay: 0.0005

  scheduler:
    type: CosineAnnealingLR
    T_max: 100
    eta_min: 0.00001

  loss_function:
    classification: CrossEntropy
    bbox_regression: GIoU

  early_stopping:
    enabled: true
    patience: 10
    metric: val_map50

hardware:
  device: "cuda / cpu / mps"
  gpu_name: "GPU 이름 (예: Tesla T4)"
  num_gpus: 1
  mixed_precision: true/false

results:
  training:
    total_time: "X hours Y minutes"
    best_epoch: XX
    final_train_loss: 0.XXX
    final_val_loss: 0.XXX

  validation:
    map50: 0.XXX        # mAP@IoU=0.5
    map50_95: 0.XXX     # mAP@IoU=0.5:0.95
    precision: 0.XXX
    recall: 0.XXX

  kaggle:
    public_score: 0.XXX   # Public Leaderboard
    private_score: null   # 대회 종료 후
    submission_id: "제출 ID"

  inference:
    fps: XX              # Frames per second
    inference_time: "X ms per image"

analysis:
  strengths:
    - "잘된 점 1"
    - "잘된 점 2"

  weaknesses:
    - "부족한 점 1"
    - "부족한 점 2"

  observations:
    - "관찰 사항 1 (예: 작은 알약 검출 여전히 어려움)"
    - "관찰 사항 2"

  comparison_to_baseline:
    metric: "비교 지표 (예: mAP@50)"
    baseline_value: 0.XXX
    current_value: 0.XXX
    improvement: "+X.X% / -X.X%"

conclusion:
  success: true/false
  decision: "계속 진행 / 중단 / 수정 후 재시도"

next_steps:
  - "다음 시도할 것 1"
  - "다음 시도할 것 2"

artifacts:
  model_checkpoint: "experiments/exp_XXX/checkpoints/best.pt"
  training_log: "experiments/exp_XXX/logs/train.log"
  tensorboard: "experiments/exp_XXX/tensorboard"
  predictions: "experiments/exp_XXX/predictions/"
  visualizations:
    - "experiments/exp_XXX/loss_curve.png"
    - "experiments/exp_XXX/metrics.png"
    - "experiments/exp_XXX/sample_predictions.png"

notes: |
  추가 메모 사항
  - 특이사항
  - 재현 시 주의사항
  - 알아두면 좋은 점

tags:
  - "태그1 (예: baseline, yolo, augmentation)"
  - "태그2"

reproducibility:
  random_seed: 42
  cudnn_deterministic: true
  cudnn_benchmark: false
  environment: "requirements.txt or conda env export"
